//  Copyright (C) 2014 Michael J. Keith, University of Manchester
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include <inttypes.h>
#include <fstream>
#include <vector>
#include <cstdlib>
#include <TKlog.h>

// include header generated by makeheaders
#include "Psrthyme.hpp"

#if INTERFACE
#include <boost/shared_ptr.hpp>
class Psrthyme {
   public:
	  typedef boost::shared_ptr<Psrthyme> Ptr;
   private:
	  Psrthyme(){
	  }
   public:
	  static void setup();
};
#endif



void Psrthyme::setup(){
   PsrthymeTelescope::setup();
}
