//  Copyright (C) 2014 Michael J. Keith, University of Manchester
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include <inttypes.h>

// include header generated by makeheaders
#include "PsrthymeComponent.hpp"

#if INTERFACE
#include <boost/shared_ptr.hpp>
#include <iostream>
class PsrthymeComponent {
   public:
	  virtual double getValue(double phase) const =0 ;
	  virtual double getValue(double p0, double p1)const =0;
	  virtual void write(std::ostream &out)=0;
	  typedef boost::shared_ptr<PsrthymeComponent>  Ptr;
};

#endif
