//  Copyright (C) 2014 Michael J. Keith, University of Manchester
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include <inttypes.h>
#include <TKmatrix.h>
#include <stdexcept>


// include header generated by makeheaders
#include "PsrthymeMatrix.hpp"

#if INTERFACE
#include <boost/shared_ptr.hpp>
#include <vector>
#include <sstream>
class PsrthymeMatrix {
   private:
	  uint64_t x;
	  uint64_t y;
	  double ** matrix;
   public:
	  typedef boost::shared_ptr<PsrthymeMatrix>  Ptr;
	  PsrthymeMatrix(const uint64_t x);
	  PsrthymeMatrix(const uint64_t x, const uint64_t y);
	  ~PsrthymeMatrix();
	  double* &operator[](const uint64_t r){
		 return matrix[r];
	  }
	  std::string toSimpleString(){
		 std::stringstream ss;
		 ss << "("<<this->x<<","<<this->y<<")";
		 return ss.str();
	  }
	  double ** c_arr(){
		 return this->matrix;
	  }

	  const Ptr operator*(const Ptr m);
	  const Ptr operator*(const PsrthymeMatrix &m);
	  const std::vector<double> operator*(const std::vector<double> &vec);
	  const std::vector<double> operator*(const boost::shared_ptr<double[]> vec);
	  void addDiagonal(std::vector<double> diag);
	  void addDiagonal(double diag);
	  void addCVF(std::vector<double> diag);
};

#endif
PsrthymeMatrix::PsrthymeMatrix(const uint64_t x){
   this->matrix=malloc_uinv(x);
   this->x=x;
   this->y=x;
}
PsrthymeMatrix::PsrthymeMatrix(const uint64_t x, const uint64_t y){
   this->matrix=malloc_blas(x,y);
   this->x=x;
   this->y=y;
}
PsrthymeMatrix::~PsrthymeMatrix(){
   free_uinv(this->matrix);
}

const PsrthymeMatrix::Ptr PsrthymeMatrix::operator*(const PsrthymeMatrix::Ptr m){
   if (this->y != m->x){
	  LOGERR << "Can't multiply these matricies" <<std::endl;
	  LOGERR << this->toSimpleString() <<std::endl;
	  LOGERR << m->toSimpleString() <<std::endl;
   throw std::invalid_argument("Can't multiply these matricies");
   }
   PsrthymeMatrix::Ptr out = PsrthymeMatrix::Ptr(new PsrthymeMatrix(this->x,m->y));
   TKmultMatrix(this->matrix,m->matrix,this->x, this->y, m->y,out->matrix);
   return out;
}
const PsrthymeMatrix::Ptr PsrthymeMatrix::operator*(const PsrthymeMatrix &mm){
   const PsrthymeMatrix* m=&mm;
   if (this->y != m->x)throw std::invalid_argument("Can't multiply these matricies");
   PsrthymeMatrix::Ptr out = PsrthymeMatrix::Ptr(new PsrthymeMatrix(this->x,m->y));
   TKmultMatrix(this->matrix,m->matrix,this->x, this->y, m->y,out->matrix);
   return out;
}

const std::vector<double> PsrthymeMatrix::operator*(const std::vector<double> &vec){
   if (this->y != vec.size()){
	  LOGERR << "Can't multiply these matricies" <<std::endl;
	  LOGERR << this->toSimpleString() <<std::endl;
	  LOGERR << vec.size() <<std::endl;
	  throw std::invalid_argument("Can't multiply these matricies");
   }
   std::vector<double> out;
   out.resize(this->x,0.0);
   TKmultMatrixVec(this->matrix,(double*) &vec[0],this->x, this->y, &out[0]);
   return out;
}


const std::vector<double> PsrthymeMatrix::operator*(const boost::shared_ptr<double[]> vec){
   std::vector<double> out;
   out.resize(this->x,0.0);
   TKmultMatrixVec(this->matrix,(double*) &vec[0],this->x, this->y, &out[0]);
   return out;
}



void PsrthymeMatrix::addDiagonal(std::vector<double> diag){
   if(this->x!=this->y)throw std::invalid_argument("Can't add diagonal of non-square matrix");
   for(uint64_t i=0;i<this->x; i++){
		this->matrix[i][i] += diag[i];
   }
}
void PsrthymeMatrix::addDiagonal(double diag){
   if(this->x!=this->y){
	  LOGERR << "Can't add diagonal of non-square matrix x="<<this->x<<"y= "<<y <<std::endl;
	  this->toSimpleString();
	  throw std::invalid_argument("Can't add diagonal of non-square matrix");
   }
   for(uint64_t i=0;i<this->x; i++){
		this->matrix[i][i] += diag;
   }
}

void PsrthymeMatrix::addCVF(std::vector<double> diag){
   if(x!=y)throw std::invalid_argument("Can't make cvm from cvf for non-square matrix");
   for(int64_t i=0;i<this->x; i++){
	  for(int64_t j=0;j<this->y; j++){
		 int64_t k=i-j;
		 if(k<0)k+=this->x;
		 this->matrix[i][j] = diag[k];
	  }
   }

}
