//  Copyright (C) 2014 Michael J. Keith, University of Manchester
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include <inttypes.h>

// include header generated by makeheaders
#include "PsrthymeArchive.hpp"

#if INTERFACE
#include <boost/shared_ptr.hpp>
class PsrthymeArchive {
   private:
   public:
	  typedef boost::shared_ptr<PsrthymeArchive> Ptr;
	  virtual int64_t get_MJD();
	  virtual uint64_t getStartTime(); // from MJD
	  virtual uint64_t getNsub();
	  virtual uint64_t getNbins();
	  virtual uint64_t getNchans();
	  virtual uint64_t getNpol();
	  virtual PsrthymeTelescope getTelescope();
	  virtual PsrthymeProfile::Ptr getProfile(uint64_t isubint, uint64_t ichan, uint64_t ipol);
};
#endif

