//  Copyright (C) 2014 Michael J. Keith, University of Manchester
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include <inttypes.h>

// include header generated by makeheaders
#include "PsrthymeWritableArchive.hpp"

#if INTERFACE
#include <boost/shared_ptr.hpp>
class PsrthymeWritableArchive : public PsrthymeArchive{
   private:
   public:
	  typedef boost::shared_ptr<PsrthymeWritableArchive> Ptr;
	  virtual void set_filename(std::string str);
	  virtual void write();
};
#endif

