//  Copyright (C) 2014 Michael J. Keith, University of Manchester
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include <inttypes.h>
#include <limits>
#include <map>
#include <boost/foreach.hpp>

// include header generated by makeheaders
#include "PsrthymeFitter.hpp"
#define TIMEIT 1

#if INTERFACE
#include <list>
#include <boost/shared_ptr.hpp>

class PsrthymeGenericFitter {
   private:
   public:
	  typedef boost::shared_ptr<PsrthymeGenericFitter> Ptr;
	  virtual void setTemplate(PsrthymeTemplate::Ptr tmpl)=0;
	  virtual PsrthymeResult::Ptr fitTo(PsrthymeProfile::Ptr obs)=0;
};

#endif
