//  Copyright (C) 2014 Michael J. Keith, University of Manchester
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include <inttypes.h>
#include <cmath>

// include header generated by makeheaders
#include "VonMisesComponent.hpp"

#if INTERFACE
#include <boost/shared_ptr.hpp>
class VonMisesComponent : public PsrthymeComponent{
   private:
	  double height;
	  double centre;
	  double concentration;
	  double delta_phase;
   public:
	  double getValue(double phase) const {
		 return this->height * exp((cos(2.0*M_PI*(phase - this->centre)) -1)*this->concentration);
	  }

	  double getValue(double p0, double p1) const{
		 double ret = this->getValue(p0);
		 uint_fast32_t n=1;
		 for (double p = p0+this->delta_phase; p < p1; p++){
			ret+=this->getValue(p);
			n++;
		 }	
		 return ret/double(n);
	  }
	  void write(std::ostream &out){
		 out << "\t\tVON_MISES " << this->centre << "\t" << this->concentration << "\t" << this->height << std::endl;
	  }
	  VonMisesComponent(double height, double centre, double concentration){
		 this->height = height;
		 this->centre = centre;
		 this->concentration = concentration;
		 this->delta_phase=1.0/4096;
	  }
	  typedef boost::shared_ptr<VonMisesComponent>  Ptr;
};

#endif
