#!/bin/bash

mode="$1"

if [[ "$mode" == "O" ]] ; then
	# optimised
	export CFLAGS="-O3 -g0 -march=native -mno-avx -pipe -fomit-frame-pointer"
	export CXXFLAGS="$CFLAGS"
elif [[ "$mode" == "D" ]] ; then
	export CFLAGS="-O0 -g3"
	export CXXFLAGS="$CFLAGS"
elif [[ "$mode" == "P" ]] ; then
	export CFLAGS="-pg"
	export CXXFLAGS="$CFLAGS"
	export LDFLAGS='-pg'
else
	export CFLAGS="-O2 -g"
	export CXXFLAGS="$CFLAGS"
fi



echo "CFLAGS='$CFLAGS'"
echo "LDFLAGS='$LDFLAGS'"

./configure --prefix=/usr/local
