//  Copyright (C) 2014 Michael J. Keith, University of Manchester
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include <inttypes.h>
#include <cpgplot.h>
#include <TKlog.h>

// include header generated by makeheaders
#include "PgPlotText.hpp"

#if INTERFACE
#include <boost/shared_ptr.hpp>
#include <string>
class PgPlotText {
   public:
	  typedef boost::shared_ptr<PgPlotText> Ptr;
	  std::string txt;
	  uint64_t colorIndex;
	  double x,y,just,angle,size;
	  PgPlotText(std::string txt, double x, double y);
	  void draw();
};
#endif

void PgPlotText::draw(){
   cpgsci(this->colorIndex);
   cpgsch(this->size);
   cpgptxt(this->x, this->y, this->just, this->angle,this->txt.c_str());
}

PgPlotText::PgPlotText(std::string txt, double x, double y){
   this->txt=txt;
   this->x=x;
   this->y=y;
   this->just=0.0;
   this->angle=0.0;
   this->size=1.0;
   this->colorIndex=PgPlot::INK;
}


