//  Copyright (C) 2014 Michael J. Keith, University of Manchester
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include <inttypes.h>
#include <cpgplot.h>

// include header generated by makeheaders
#include "PsrthymePlotter.hpp"

#if INTERFACE
class PsrthymePlotter {
   public:
	  PsrthymePlotter(); // constructor
}

#endif

PsrthymePlotter::PsrthymePlotter() {

}

