//  Copyright (C) 2014 Michael J. Keith, University of Manchester
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include <inttypes.h>
#include <string>
#include <fstream>
#include <sstream>
#include <boost/algorithm/string/trim.hpp>
#include <boost/lexical_cast.hpp>


// include header generated by makeheaders
#include "psrthyme-template.hpp"

#if INTERFACE
#include <iostream>
#include <vector>
#include <boost/shared_ptr.hpp>
class PsrthymeTemplate {
   private:
	  std::string name;
	  PsrthymeTemplate(){}; // constructor
	  std::vector<PsrthymeProfile::Ptr> profiles;
   public:
	  typedef boost::shared_ptr<PsrthymeTemplate>  Ptr;
	  static PsrthymeTemplate::Ptr read(const char* filename);

	  void write(std::ostream &out);
	  void addProfile(PsrthymeProfile::Ptr profile){
		 this->profiles.push_back(profile);
	  }
};



#define strings_equal(a,b) (a.compare(b)==0)
#endif

bool isNumber(std::string str){
   try 
   {
	  double x = boost::lexical_cast<double>(str); // double could be anything with >> operator.
	  return true;
   }
   catch(...) { 
	  return false;
   }
}

PsrthymeTemplate::Ptr PsrthymeTemplate::read(const char* filename){
   PsrthymeTemplate::Ptr tmpl = PsrthymeTemplate::Ptr(new PsrthymeTemplate());

   std::ifstream infile(filename);
   std::string line;
   std::string str;

   uint64_t iComp=-1;
   uint64_t iProf=-1;

   while (std::getline(infile, line)) {
	  boost::trim(line);


	  LOGDBG << "LINE: " << line<< std::endl;
	  if (line[0]=='#' || line[0]=='\0')continue;

	  std::stringstream ss(line);

	  ss >> str; // read the first keyword

	  LOGDBG << "CMD: " << str << std::endl;

	  if (strings_equal(str,"KWTEMPLATE") || strings_equal(str,"TEMPLATE")){
		 ss >> tmpl->name;
		 LOGDBG << "NAME: " << tmpl->name << std::endl;
		 continue;
	  }
	  if (strings_equal(str,"KWPROFILE") || strings_equal(str,"PROFILE")){
		 ss >> str;
		 PsrthymeProfile::Ptr profile = PsrthymeProfile::Ptr(new PsrthymeProfile(str));
		 tmpl->addProfile(profile);
		 continue;
	  }

	  if (strings_equal(str,"VON_MISES") || isNumber(str) ){
		 double height,centre,conc;
		 if(!strings_equal(str,"VON_MISES")){
			ss.seekg(0);
		 }
		 ss >> centre;
		 ss >> conc;
		 ss >> height;
		 VonMisesComponent::Ptr component = VonMisesComponent::Ptr(new VonMisesComponent(height,centre,conc));
		 tmpl->profiles.back()->addComponent(component);
	  }
   }
   return tmpl;
}



void PsrthymeTemplate::write(std::ostream &out){
   out << "TEMPLATE \t" << this->name << std::endl;
   uint64_t iComp,iProf;
   for (iProf=0; iProf < this->profiles.size(); iProf++){
	  this->profiles[iProf]->write(out);
   }

   out << "# END    \t"<<this->name << std::endl;
}
