//  Copyright (C) 2014 Michael J. Keith, University of Manchester
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include <inttypes.h>

// include header generated by makeheaders
#include "psrthyme-observation.hpp"

#if INTERFACE
#include <vector>
#include <list>
class PsrthymeObservation {
   private:
	  std::vector<double> profile;
	  double freq;
	  uint64_t imjd;
	  double fmjd;
   public:
	  PsrthymeObservation() {
	  } 
};

#endif



