//  Copyright (C) 2014 Michael J. Keith, University of Manchester
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include <inttypes.h>

// include header generated by makeheaders
#include "PsrthymeResult.hpp"

#if INTERFACE
#include <vector>
#include <list>
#include <boost/shared_ptr.hpp>
class PsrthymeResult {
   public:
	  typedef boost::shared_ptr<PsrthymeResult> Ptr;
	  SparseList::Ptr chisq_space;
	  PsrthymeTemplate::Ptr tmpl;
	  PsrthymeObservation::Ptr obsn;
	  std::vector<double> amp_values;
	  std::vector<double> amp_errors;
	  std::vector<double> data_cov;
	  PsrthymeMatrix::Ptr amp_cvm;
	  uint64_t nfree;
	  uint64_t nfit;
	  double phase;
	  double error;
	  PsrthymeResult() {
	  };
	  std::vector<double> best_profile;
	  std::vector<double> residual;
};
#endif


