//  Copyright (C) 2014 Michael J. Keith, University of Manchester
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include <inttypes.h>
#include <TKmatrix.h>
#include <stdexcept>


// include header generated by makeheaders
#include "psrthyme-matrix.hpp"

#if INTERFACE
#include <boost/shared_ptr.hpp>
#include <vector>
class PsrthymeMatrix {
   private:
	  double ** matrix;
	  uint64_t x;
	  uint64_t y;
   public:
	  typedef boost::shared_ptr<PsrthymeMatrix>  Ptr;
	  PsrthymeMatrix(const uint64_t x);
	  PsrthymeMatrix(const uint64_t x, const uint64_t y);
	  ~PsrthymeMatrix();
	  Ptr operator*(const PsrthymeMatrix::Ptr m);
	  std::vector<double> operator*(const std::vector<double> &vec);
	  void addDiagonal(std::vector<double> diag);
	  void addDiagonal(double diag);
	  void addCVF(std::vector<double> diag);
};

#endif
PsrthymeMatrix::PsrthymeMatrix(const uint64_t x){
   this->matrix=malloc_uinv(x);
   this->x=x;
   this->y=y;
}
PsrthymeMatrix::PsrthymeMatrix(const uint64_t x, const uint64_t y){
   this->matrix=malloc_blas(x,y);
   this->x=x;
   this->y=y;
}
PsrthymeMatrix::~PsrthymeMatrix(){
   free_uinv(this->matrix);
}

PsrthymeMatrix::Ptr PsrthymeMatrix::operator*(const PsrthymeMatrix::Ptr m){
   if (this->y != m->x)throw std::invalid_argument("Can't multiply these matricies");
   PsrthymeMatrix::Ptr out = PsrthymeMatrix::Ptr(new PsrthymeMatrix(this->x,m->y));
   TKmultMatrix(this->matrix,m->matrix,this->x, this->y, m->y,out->matrix);
   return out;
}
std::vector<double> PsrthymeMatrix::operator*(const std::vector<double> &vec){
   std::vector<double> out(vec);
   TKmultMatrixVec(this->matrix,(double*) &vec[0],this->x, this->y, (double*)&out[0]);
   return out;
}

void PsrthymeMatrix::addDiagonal(std::vector<double> diag){
   if(x!=y)throw std::invalid_argument("Can't add diagonal of non-square matrix");
   for(uint64_t i=0;i<this->x; i++){
		this->matrix[i][i] += diag[i];
   }
}
void PsrthymeMatrix::addDiagonal(double diag){
   if(x!=y)throw std::invalid_argument("Can't add diagonal of non-square matrix");
   for(uint64_t i=0;i<this->x; i++){
		this->matrix[i][i] += diag;
   }
}

void PsrthymeMatrix::addCVF(std::vector<double> diag){
   if(x!=y)throw std::invalid_argument("Can't add diagonal of non-square matrix");
   for(int64_t i=0;i<this->x; i++){
	  for(int64_t j=0;j<this->y; j++){
		 int64_t k=i-j;
		 if(k<0)k+=this->x;
		 this->matrix[i][j] += diag[k];
	  }
   }

}
