//  Copyright (C) 2014 Michael J. Keith, University of Manchester
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include <inttypes.h>

// include header generated by makeheaders
#include "psrthyme-fitter.hpp"

#if INTERFACE
class PsrthymeFitter {
   public:
	  PsrthymeFitter(); // constructor
}

#endif

PsrthymeFitter::PsrthymeFitter() {

}

