//  Copyright (C) 2014 Michael J. Keith, University of Manchester
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include <inttypes.h>
#include <cmath>

// include header generated by makeheaders
#include "VonMisesComponent.hpp"

#if INTERFACE
#include <boost/shared_ptr.hpp>
class VonMisesComponent : public PsrthymeComponent{
   private:
	  double height;
	  double centre;
	  double concentration;
   public:
	  double getValue(double phase){
		 return this->height * exp((cos(2.0*M_PI*(phase - this->centre)) -1)*this->concentration);
	  }
	  void write(std::ostream &out){
		 out << "\t\tVON_MISES " << this->centre << "\t" << this->concentration << "\t" << this->height << std::endl;
	  }
	  VonMisesComponent(double height, double centre, double concentration){
		 this->height = height;
		 this->centre = centre;
		 this->concentration = concentration;
	  }
	  typedef boost::shared_ptr<VonMisesComponent>  Ptr;
};

#endif
